/**
 * Rhombic enneacontahedron — the zonohedron generated by the ten three-fold
 * axes of the icosahedron: 90 rhombic faces (60 broad + 30 slim), 92
 * vertices, 180 equal edges, ten belts of 18 rhombi.
 *
 * Built directly as a zonotope, without a hull: for generators g₁…g₁₀ with
 * no three coplanar, each pair (i, j) spans two opposite faces. With
 * u = ±(gᵢ × gⱼ) the face normal, the face centre is ½ Σₖ sign(gₖ·u) gₖ over
 * the other eight generators, and its corners are centre ± gᵢ/2 ± gⱼ/2.
 *
 * The axes are the dodecahedron-type directions paired with
 * `icosahedronVerts()` — the same family rhombic.js uses (see its chirality
 * note) — so the solid shares the φ-family orientation of the other bases.
 *
 * Vertices sit at three radii; normalizePoints divides by the outermost, so
 * Size keeps meaning circumdiameter.
 */

import { PHI, cubeVerts, normalizePoints } from "./platonic.js";

/** One unit vector per three-fold axis (ten antipodal pairs → ten axes). */
function threeFoldAxes() {
  const pts = cubeVerts();
  for (const s1 of [-1, 1]) {
    for (const s2 of [-1, 1]) {
      pts.push([0, s1 * PHI, s2 / PHI]);
      pts.push([s1 / PHI, 0, s2 * PHI]);
      pts.push([s1 * PHI, s2 / PHI, 0]);
    }
  }
  const axes = [];
  for (const p of pts) {
    // Keep the representative whose first non-zero coordinate is positive.
    const lead = p.find((c) => Math.abs(c) > 1e-12);
    if (!(lead > 0)) continue;
    const l = Math.hypot(p[0], p[1], p[2]);
    axes.push([p[0] / l, p[1] / l, p[2] / l]);
  }
  return axes;
}

/** @returns {Float64Array} flat xyz, unit circumradius; 92 vertices */
export function rhombicEnneacontaPoints() {
  const g = threeFoldAxes();
  const n = g.length;
  /** @type {Map<string, number[]>} */
  const verts = new Map();
  const add = (p) => {
    // Shared corners arrive from up to six faces with float noise ≈ 1e-16.
    const key = p.map((c) => Math.round(c * 1e9)).join(",");
    if (!verts.has(key)) verts.set(key, p);
  };
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const a = g[i], b = g[j];
      const u = [
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
      ];
      for (const side of [1, -1]) {
        const c = [0, 0, 0];
        for (let k = 0; k < n; k++) {
          if (k === i || k === j) continue;
          const s = side * (g[k][0] * u[0] + g[k][1] * u[1] + g[k][2] * u[2]) > 0 ? 0.5 : -0.5;
          c[0] += s * g[k][0];
          c[1] += s * g[k][1];
          c[2] += s * g[k][2];
        }
        for (const si of [0.5, -0.5]) {
          for (const sj of [0.5, -0.5]) {
            add([
              c[0] + si * a[0] + sj * b[0],
              c[1] + si * a[1] + sj * b[1],
              c[2] + si * a[2] + sj * b[2],
            ]);
          }
        }
      }
    }
  }
  return normalizePoints([...verts.values()]);
}
